version: '3.2'
services:
  database:
    restart: always
    container_name: ${CONTAINER_PREFIX}_database
    tty: true
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    build:
      context: ./.docker/images/mysql
      args:
        - DATABASE_IMAGE=${DATABASE_IMAGE}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_INITDB_SKIP_TZINFO: 1
    expose:
      - "3306"
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - sql-data:/var/lib/mysql
    depends_on:
      - nginx
  nginx:
    restart: always
    container_name: ${CONTAINER_PREFIX}_nginx
    working_dir: /var/www/
    build:
      context: ./.docker/images/nginx
      args:
        - APP_HOST=${APP_HOST}
    volumes:
      - ${APP_SRC}:/var/www/
      - ./.docker/images/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/images/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - ${NGINX_PORT_80}:80
    depends_on:
      - php-fpm
  php-fpm:
    user: www
    container_name: ${CONTAINER_PREFIX}_php-fpm
    working_dir: /var/www/
    expose:
      - 9000
    build:
      context: ./.docker/images/php-fpm
      args:
        - PHP_VERSION=${PHP_VERSION}
        - ENABLE_XDEBUG=${ENABLE_XDEBUG}
    volumes:
      - ${APP_SRC}:/var/www/:cached
  redis:
    restart: always
    container_name: ${CONTAINER_PREFIX}_redis
    build:
      context: ./.docker/images/redis
    expose:
      - 6379
  mailhog:
    restart: unless-stopped
    container_name: ${CONTAINER_PREFIX}_mailhog
    build:
      context: ./.docker/images/mailhog
    expose:
      - "1025"
    ports:
      - ${MAILHOG_PORT}:8025
volumes:
  sql-data:
