#!/bin/bash

source .env
source .docker/scripts/include/wp.sh

is_wp_installed

TARGET_ENV="${APP_SRC}/.env"

WP_SALTS=$(wget https://api.wordpress.org/secret-key/1.1/salt/ -q -O -)
# Remove 'echo'
WP_SALTS=${WP_SALTS//echo}

SED_OPTIONS=""
if [[ "$OSTYPE" == "darwin"* ]]; then
  SED_OPTIONS="\'\'"
fi

rm -f ${APP_SRC}/.env
cp .docker/wordpress/.env.example ${APP_SRC}/.env
cp .docker/wordpress/composer.json ${APP_SRC}/
cp .docker/wordpress/wp-config.php ${APP_SRC}/

sed -i $SED_OPTIONS "s/DATABASE_NAME=.*/DATABASE_NAME=\"$MYSQL_DATABASE\"/g" $TARGET_ENV
sed -i $SED_OPTIONS "s/DATABASE_USER=.*/DATABASE_USER=\"$MYSQL_USER\"/g" $TARGET_ENV
sed -i $SED_OPTIONS "s/DATABASE_PASSWORD=.*/DATABASE_PASSWORD=\"$MYSQL_PASSWORD\"/g" $TARGET_ENV
sed -i $SED_OPTIONS "s/DATABASE_HOST=.*/DATABASE_HOST=\"database\"/g" $TARGET_ENV


SALTS=$(curl -s https://api.wordpress.org/secret-key/1.1/salt/)
while read -r SALT; do
  SALT=${SALT/define(\'/}
  SALT=${SALT/\');/\"}
  SALT=${SALT/,/=\"}
  SALT=${SALT//[\' ]/}
  echo $SALT >> $TARGET_ENV
done <<< "$SALTS"

CURRENT_DIR=$(pwd)
cd $APP_SRC && composer install

wp core install --url=${APP_HOST} --title="Blog" --admin_user=${WP_ADMIN_USER} --admin_email=${WP_ADMIN_EMAIL} --admin_password=${WP_ADMIN_PASSWORD} --skip-email

cd $CURRENT_DIR

exit 0
