#!/bin/bash

source .env

# Download WordPress core into $APP_SRC folder
mkdir -p ${APP_SRC}
docker-compose run php-fpm bash -c "export WP_CLI_CACHE_DIR=/dev/null && wp --allow-root core download --locale=${WP_LOCALE} --path=/var/www"

# Install WordPress
.docker/scripts/wp-init